# Generated by Django 4.0 on 2022-05-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmsDetails',
            new_name='FilmDetails',
        ),
        migrations.RenameModel(
            old_name='SessionsTime',
            new_name='TimeSessions',
        ),
    ]
