# Generated by Django 4.0 on 2022-05-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_rename_filmsdetails_filmdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahalls',
            name='id_session',
        ),
        migrations.RemoveField(
            model_name='cinemas',
            name='film_id',
        ),
        migrations.RemoveField(
            model_name='films',
            name='hall_id',
        ),
        migrations.RemoveField(
            model_name='films',
            name='id_session',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='hall_id',
        ),
        migrations.AddField(
            model_name='cinemahalls',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.timesessions', verbose_name='Сеанс'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.films', verbose_name='Назва фільму'),
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.films', verbose_name='Назва фільму'),
        ),
        migrations.AddField(
            model_name='films',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinemahalls', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='films',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.timesessions', verbose_name='Сеанс'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='hall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinemahalls', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='cinemahalls',
            name='row_count',
            field=models.IntegerField(verbose_name='Кількість рядів'),
        ),
        migrations.AlterField(
            model_name='cinemahalls',
            name='ticket_count',
            field=models.IntegerField(verbose_name='Кількість квитків'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='city',
            field=models.CharField(max_length=25, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='age',
            field=models.IntegerField(verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='director',
            field=models.CharField(max_length=40, verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='duration',
            field=models.FloatField(verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='genre',
            field=models.CharField(max_length=40, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='language',
            field=models.CharField(max_length=40, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='main_roles',
            field=models.TextField(verbose_name='У головних ролях'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='production',
            field=models.CharField(max_length=40, verbose_name='Виробництво'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='rental_period_from',
            field=models.DateTimeField(verbose_name='Період прокату'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='scenario',
            field=models.TextField(verbose_name='Сценарій'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='year',
            field=models.IntegerField(verbose_name='Рік'),
        ),
        migrations.AlterField(
            model_name='films',
            name='film_title',
            field=models.CharField(max_length=25, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг фільму'),
        ),
        migrations.AlterField(
            model_name='films',
            name='story',
            field=models.TextField(verbose_name='Сюжет'),
        ),
        migrations.AlterField(
            model_name='films',
            name='ticket_price',
            field=models.IntegerField(verbose_name='Ціна квитка'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='purchased_ticket',
            field=models.IntegerField(verbose_name='Продані квитки'),
        ),
        migrations.AlterField(
            model_name='timesessions',
            name='time_session',
            field=models.TimeField(verbose_name='Сеанс'),
        ),
    ]
