# Generated by Django 4.0 on 2022-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_remove_cinemahalls_id_session_remove_cinemas_film_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahalls',
            options={'verbose_name': 'Кінозал', 'verbose_name_plural': 'Кінозали'},
        ),
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Кінотеатр', 'verbose_name_plural': 'Кінотеатри'},
        ),
        migrations.AlterModelOptions(
            name='filmdetails',
            options={'verbose_name': 'Деталі фільму', 'verbose_name_plural': 'Деталі фільмів'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільми'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Проданий квиток', 'verbose_name_plural': 'Продані квитки'},
        ),
        migrations.AlterModelOptions(
            name='timesessions',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеанси'},
        ),
        migrations.RemoveField(
            model_name='cinemas',
            name='address',
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='rental_period_from',
            field=models.DateField(verbose_name='Прокат від'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='rental_period_to',
            field=models.DateField(verbose_name='Прокат до'),
        ),
    ]
