# Generated by Django 4.0 on 2022-05-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_alter_cinemahalls_options_alter_cinemas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahalls',
            name='session',
        ),
    ]
