# Generated by Django 4.0 on 2022-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_remove_cinemahalls_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahalls',
            name='number_hall',
            field=models.IntegerField(default=1, verbose_name='Номер кінозалу'),
        ),
    ]
