# Generated by Django 4.0 on 2022-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_cinemahalls_number_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahalls',
            name='number_hall',
            field=models.IntegerField(verbose_name='Номер кінозалу'),
        ),
    ]
