# Generated by Django 4.0 on 2022-05-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_cinemahalls_number_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=25, verbose_name='Назва фільму')),
                ('ticket_price', models.IntegerField(verbose_name='Ціна квитка')),
                ('story', models.TextField(verbose_name='Сюжет')),
                ('poster', models.ImageField(upload_to='cinema_app/')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='FilmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('director', models.CharField(max_length=40, verbose_name='Режисер')),
                ('rental_period_from', models.DateField(verbose_name='Прокат від')),
                ('rental_period_to', models.DateField(verbose_name='Прокат до')),
                ('language', models.CharField(max_length=40, verbose_name='Мова')),
                ('genre', models.CharField(max_length=40, verbose_name='Жанр')),
                ('duration', models.FloatField(verbose_name='Тривалість')),
                ('production', models.CharField(max_length=40, verbose_name='Виробництво')),
                ('scenario', models.TextField(verbose_name='Сценарій')),
                ('main_roles', models.TextField(verbose_name='У головних ролях')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.film', verbose_name='Назва фільму')),
            ],
            options={
                'verbose_name': 'Деталі фільму',
                'verbose_name_plural': 'Деталі фільмів',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.film', verbose_name='Назва фільму')),
            ],
            options={
                'verbose_name': 'Рейтинг фільму',
                'verbose_name_plural': 'Рейтинги фільмів',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Рейтинг фільму')),
            ],
            options={
                'verbose_name': 'Зірка',
                'verbose_name_plural': 'Зірки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=5000)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.film', verbose_name='Назва фільму')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RemoveField(
            model_name='films',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='films',
            name='session',
        ),
        migrations.RenameModel(
            old_name='Cinemas',
            new_name='Cinema',
        ),
        migrations.RenameModel(
            old_name='CinemaHalls',
            new_name='CinemaHall',
        ),
        migrations.RenameModel(
            old_name='TimeSessions',
            new_name='TimeSession',
        ),
        migrations.DeleteModel(
            name='FilmDetails',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.ratingstar', verbose_name='Кількість зірок'),
        ),
        migrations.AddField(
            model_name='filmdetail',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.rating', verbose_name='Рейтинг фільму'),
        ),
        migrations.AddField(
            model_name='film',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinemahall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='film',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.timesession', verbose_name='Сеанс'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.film', verbose_name='Назва фільму'),
        ),
    ]
