# Generated by Django 4.0 on 2022-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_film_filmdetail_rating_ratingstar_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='cinema_app/static/cinema_app/images'),
        ),
    ]
