# Generated by Django 4.0 on 2022-05-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0011_cinemafilms_cities_alter_film_film_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemafilms',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cities', verbose_name='Місто'),
        ),
    ]
