# Generated by Django 4.0 on 2022-05-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0015_filmdetailview_remove_search_filmdetails_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.film', verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email автора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я автора"),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст відгука'),
        ),
        migrations.DeleteModel(
            name='FilmDetailView',
        ),
    ]
