# Generated by Django 4.0 on 2022-05-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0016_ticket_film_alter_review_email_alter_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinemahall', verbose_name='Номер залу'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchased_ticket',
            field=models.IntegerField(verbose_name='Оберіть номер квитка'),
        ),
    ]
