# Generated by Django 4.0 on 2022-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0020_alter_buffet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffet',
            name='image',
            field=models.ImageField(null=True, upload_to='cinema_app/static/cinema_app/images/buffet', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='cinema_app/static/cinema_app/images', verbose_name='Постер'),
        ),
    ]
