# Generated by Django 4.0 on 2022-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0021_alter_buffet_image_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='story',
            field=models.CharField(max_length=5000, verbose_name='Сюжет'),
        ),
    ]
