# Generated by Django 4.0 on 2022-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0022_alter_film_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='story',
            field=models.TextField(verbose_name='Сюжет'),
        ),
    ]
