# Generated by Django 4.0 on 2022-06-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0023_alter_film_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_title',
            field=models.CharField(max_length=200, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.CharField(max_length=100, null=True, verbose_name='Мова'),
        ),
    ]
